version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./data/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: olblighty
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: blight

   tde-wp:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./data/tde-wp/wp-content:/var/www/html/wp-content
     ports:
       - "8080:80"
     restart: unless-stopped
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: blight
       WORDPRESS_TABLE_PREFIX: chc

